[package]
name = "texteditor"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.30.0-alpha.5"
crossterm = "0.29"
unicode-segmentation = "1.11"
unicode-width = "0.1"
ropey = "1.6"
arboard = "3.3"